# -*- coding: utf-8 -*-
"""AI Minor Project(Shreya Gupta_10801172021).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5DDaExjUlP4NL1xG3lN6sqGdlTi-nAU
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df =pd.read_csv(r"/honeyproduction.csv")

"""Q1) Explore quantitative and qualitative variables in the dataset."""

df.info()

"""ANS 1) 
*   The above dataset shows that most of the variables in the dataset are quantitative while the state variable is found to be qualitative.
*  Also the table shows the count of null values and the datatypes.

Q2) Find the relationship betweeen numerical variables using pairplots and correlation plots. Explain what you infer from these plots.
"""

sns.pairplot(df)

sns.heatmap(data=df.corr(),annot=True)

"""ANS 2)
*  Number of colonies have a high positive correlation with total production,stocks and value of production. 
* Yield per colony does not have a high correlation with any of the features.
* Same happens in the case of priceperlb.

Q3) Look at overall trend of honey production in the US over years.
"""

plt.figure(figsize=(15,7))
sns.pointplot(x='year',y='totalprod',data=df,estimator=sum,ci=None,color='saddlebrown')
plt.title('Total Production of Honey in USA over Years' ,fontsize=30,color='purple')
plt.xlabel('Year',fontsize=20,color='red')
plt.ylabel('Total Production of Honey' ,fontsize=20,color='forestgreen')
plt.show()

"""ANS 3)

*   The overall trend of the honey production shows that the total production of honey declines the most in year 2007.

*   There is variation in production of honey with decrement along the years.

*   the highest production of honey is observed in year 1998.

Q4) Are there any patterns that can be observed between total honey production and value of production every year? How has the value of production which in some sense could be tied to demand changed every year?
"""

plt.figure(figsize=(8,8))
plt.scatter(df['year'],df['totalprod'],color='black',marker='s')
plt.scatter(df['year'],df['prodvalue'],color='gold',marker='^')
plt.title('Total Production of Honey over the years' ,fontsize=20,color='indigo')
plt.xlabel('years',fontsize=15,color='red')
plt.ylabel('Quantity',fontsize=15,color='orangered')
plt.show()

"""ANS 4)
*  In general, the total honey production increases with production value.
*  There are also some cases where production value overshoots the total production like in year 2010.
* Further, there are cases whereby total production is ahead of production quantity like in year 1998.

Q5) Observe the variation in the number of colonies over the years.
"""

plt.figure(figsize=(20,7))
sns.barplot(x=df['year'],y=df['numcol'])
plt.title('Variation in number of colonies over Years' ,fontsize=30,color='green')
plt.xlabel('Year',fontsize=20,color='red')
plt.ylabel('Number of colonies' ,fontsize=20,color='purple')

"""ANS 5)
*  The number of colonies generally show certain increment as well as decrement along the years from 1998 to 2008.
* Moreover, it is possible that certain measures might have been taken which increased the average production and even became highest in year 2010.

Q6) Analyze the variation of yield per colony over the years and the production trend at the state level, and brief out what you observed.
"""

data =df.sort_values('yieldpercol',ascending =False)
fig=plt.figure(figsize=(15,5))
plt.bar(df['year'],df['yieldpercol'],color='darkslategrey')
plt.xlabel("year")
plt.ylabel("yield per colony")
plt.title("variation of yield per colony over years",fontsize=20,color='brown')
plt.show()

"""ANS 6)
*  It is observed that the variation of yield per colony remains in the range of 80 - 120.
* The trend indicates that the average value of yield per colony was initially high but with the passage of years, it declined.
"""

honey_state = df[['totalprod','state']].groupby('state').sum()
honey_state.reset_index(level=0, inplace = True)
honey_state.sort_values(by='totalprod',ascending = False,inplace = True)
plt.figure(figsize=(20,10))
sns.barplot(x=honey_state['state'],y=honey_state['totalprod'])
plt.title('State Wise Honey Production',fontsize = 20,color='purple')
plt.xlabel('state',fontsize = 20)
plt.ylabel('total production',fontsize = 20)

"""ANS 6)
*  The most prominent honey production states of US are ND,CA,SD.
*  The SC state of US has the lowest production of honey.

Q7) Analyze what effect the declining production trend has had on the value of production.
"""

plt.figure(figsize=(10,5))
sns.pointplot(x='year',y='prodvalue', data=df, ci=None,color='green')
plt.title('Honey Production Trend',fontsize = 20,color='deeppink')
plt.xlabel('year',fontsize = 15,color='red')
plt.ylabel('total production',fontsize = 15,color='peru')
plt.xticks(rotation=90)
plt.show()

"""ANS 7)

*   The total value of production has increased over time.
*   The increasing demand has also added to the value of honey.


"""